import { Prisma } from '@prisma/client';

export const products: Prisma.ProductCreateManyInput[] = [
  {
    banner: 'banner-1.jpg',
    brand: 'Polo',
    category: "Men's Dress Shirts",
    description: 'Classic Polo style with modern comfort',
    images: ['/images/sample-products/p1-1.jpg', '/images/sample-products/p1-2.jpg'],
    isFeatured: true,
    name: 'Polo Sporting Stretch Shirt',
    numReviews: 10,
    price: new Prisma.Decimal(59.99),
    rating: new Prisma.Decimal(4.5),
    slug: 'polo-sporting-stretch-shirt',
    stock: 5,
  },
  {
    banner: 'banner-2.jpg',
    brand: 'Brooks Brothers',
    category: "Men's Dress Shirts",
    description: 'Timeless style and premium comfort',
    images: ['/images/sample-products/p2-1.jpg', '/images/sample-products/p2-2.jpg'],
    isFeatured: true,
    name: 'Brooks Brothers Long Sleeved Shirt',
    numReviews: 8,
    price: new Prisma.Decimal(85.9),
    rating: new Prisma.Decimal(4.2),
    slug: 'brooks-brothers-long-sleeved-shirt',
    stock: 10,
  },
  {
    banner: null,
    brand: 'Tommy Hilfiger',
    category: "Men's Dress Shirts",
    description: 'A perfect blend of sophistication and comfort',
    images: ['/images/sample-products/p3-1.jpg', '/images/sample-products/p3-2.jpg'],
    isFeatured: false,
    name: 'Tommy Hilfiger Classic Fit Dress Shirt',
    numReviews: 3,
    price: new Prisma.Decimal(99.95),
    rating: new Prisma.Decimal(4.9),
    slug: 'tommy-hilfiger-classic-fit-dress-shirt',
    stock: 0,
  },
  {
    banner: null,
    brand: 'Calvin Klein',
    category: "Men's Dress Shirts",
    description: 'Streamlined design with flexible stretch fabric',
    images: ['/images/sample-products/p4-1.jpg', '/images/sample-products/p4-2.jpg'],
    isFeatured: false,
    name: 'Calvin Klein Slim Fit Stretch Shirt',
    numReviews: 5,
    price: new Prisma.Decimal(39.95),
    rating: new Prisma.Decimal(3.6),
    slug: 'calvin-klein-slim-fit-stretch-shirt',
    stock: 10,
  },
  {
    banner: null,
    brand: 'Polo',
    category: "Men's Dress Shirts",
    description: 'Iconic Polo design with refined oxford fabric',
    images: ['/images/sample-products/p5-1.jpg', '/images/sample-products/p5-2.jpg'],
    isFeatured: false,
    name: 'Polo Ralph Lauren Oxford Shirt',
    numReviews: 18,
    price: new Prisma.Decimal(79.99),
    rating: new Prisma.Decimal(4.7),
    slug: 'polo-ralph-lauren-oxford-shirt',
    stock: 6,
  },
  {
    banner: null,
    brand: 'Polo',
    category: "Men's Sweatshirts",
    description: 'Soft, stylish, and perfect for laid-back days',
    images: ['/images/sample-products/p6-1.jpg', '/images/sample-products/p6-2.jpg'],
    isFeatured: true,
    name: 'Polo Classic Pink Hoodie',
    numReviews: 12,
    price: new Prisma.Decimal(99.99),
    rating: new Prisma.Decimal(4.6),
    slug: 'polo-classic-pink-hoodie',
    stock: 8,
  },
];
